<?php

return [
    'default' => [
        'name' => 'Default',
        'primary' => '#3B82F6',        // Blue - Main actions, headings
        'secondary' => '#10B981',      // Green - Secondary actions
        'accent' => '#8B5CF6',         // Purple - Highlights, badges
        'success' => '#10B981',        // Green - Success messages
        'warning' => '#F59E0B',        // Amber - Warnings
        'danger' => '#EF4444',         // Red - Errors, delete actions
        'info' => '#3B82F6',           // Blue - Information
        'sidebar_bg' => '#111827',     // Dark Gray - Sidebar background
        'sidebar_text' => '#FFFFFF',   // White - Sidebar text
        'text_primary' => '#111827',   // Almost black - Main text
        'text_secondary' => '#6B7280', // Gray - Secondary text
        'text_muted' => '#9CA3AF',     // Light gray - Muted text
        'border' => '#E5E7EB',         // Light gray - Borders
        'background' => '#F3F4F6',     // Very light gray - Page background
        'card_bg' => '#FFFFFF',        // White - Card backgrounds
    ],
    'ocean' => [
        'name' => 'Ocean',
        'primary' => '#0EA5E9',
        'secondary' => '#06B6D4',
        'accent' => '#3B82F6',
        'success' => '#06B6D4',
        'warning' => '#F59E0B',
        'danger' => '#EF4444',
        'info' => '#0EA5E9',
        'sidebar_bg' => '#0C4A6E',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#0C4A6E',   // Dark ocean blue - Main text
        'text_secondary' => '#0369A1', // Ocean blue - Secondary text
        'text_muted' => '#0284C7',     // Sky blue - Muted text
        'border' => '#BAE6FD',         // Light blue - Borders
        'background' => '#F0F9FF',
        'card_bg' => '#FFFFFF',
    ],
    'sunset' => [
        'name' => 'Sunset',
        'primary' => '#F97316',
        'secondary' => '#EF4444',
        'accent' => '#FBBF24',
        'success' => '#10B981',
        'warning' => '#FBBF24',
        'danger' => '#EF4444',
        'info' => '#F97316',
        'sidebar_bg' => '#7C2D12',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#7C2D12',   // Dark orange - Main text
        'text_secondary' => '#C2410C', // Orange - Secondary text
        'text_muted' => '#EA580C',     // Bright orange - Muted text
        'border' => '#FED7AA',         // Light orange - Borders
        'background' => '#FFF7ED',
        'card_bg' => '#FFFFFF',
    ],
    'forest' => [
        'name' => 'Forest',
        'primary' => '#10B981',
        'secondary' => '#059669',
        'accent' => '#84CC16',
        'success' => '#10B981',
        'warning' => '#F59E0B',
        'danger' => '#EF4444',
        'info' => '#06B6D4',
        'sidebar_bg' => '#064E3B',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#064E3B',   // Dark green - Main text
        'text_secondary' => '#047857', // Forest green - Secondary text
        'text_muted' => '#059669',     // Emerald - Muted text
        'border' => '#BBF7D0',         // Light green - Borders
        'background' => '#F0FDF4',
        'card_bg' => '#FFFFFF',
    ],
    'lavender' => [
        'name' => 'Lavender',
        'primary' => '#8B5CF6',
        'secondary' => '#A78BFA',
        'accent' => '#C084FC',
        'success' => '#10B981',
        'warning' => '#F59E0B',
        'danger' => '#EF4444',
        'info' => '#8B5CF6',
        'sidebar_bg' => '#4C1D95',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#4C1D95',   // Dark purple - Main text
        'text_secondary' => '#6D28D9', // Purple - Secondary text
        'text_muted' => '#7C3AED',     // Violet - Muted text
        'border' => '#E9D5FF',         // Light purple - Borders
        'background' => '#FAF5FF',
        'card_bg' => '#FFFFFF',
    ],
    'crimson' => [
        'name' => 'Crimson',
        'primary' => '#DC2626',
        'secondary' => '#EF4444',
        'accent' => '#F87171',
        'success' => '#10B981',
        'warning' => '#F59E0B',
        'danger' => '#DC2626',
        'info' => '#3B82F6',
        'sidebar_bg' => '#7F1D1D',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#7F1D1D',   // Dark red - Main text
        'text_secondary' => '#991B1B', // Crimson - Secondary text
        'text_muted' => '#B91C1C',     // Red - Muted text
        'border' => '#FECACA',         // Light red - Borders
        'background' => '#FEF2F2',
        'card_bg' => '#FFFFFF',
    ],
    'midnight' => [
        'name' => 'Midnight',
        'primary' => '#1E3A8A',
        'secondary' => '#3B82F6',
        'accent' => '#60A5FA',
        'success' => '#10B981',
        'warning' => '#F59E0B',
        'danger' => '#EF4444',
        'info' => '#3B82F6',
        'sidebar_bg' => '#0F172A',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#1E3A8A',   // Dark blue - Main text
        'text_secondary' => '#1E40AF', // Blue - Secondary text
        'text_muted' => '#2563EB',     // Bright blue - Muted text
        'border' => '#DBEAFE',         // Light blue - Borders
        'background' => '#F8FAFC',
        'card_bg' => '#FFFFFF',
    ],
    'amber' => [
        'name' => 'Amber',
        'primary' => '#F59E0B',
        'secondary' => '#FBBF24',
        'accent' => '#FCD34D',
        'success' => '#10B981',
        'warning' => '#F59E0B',
        'danger' => '#EF4444',
        'info' => '#3B82F6',
        'sidebar_bg' => '#78350F',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#78350F',   // Dark amber - Main text
        'text_secondary' => '#92400E', // Amber brown - Secondary text
        'text_muted' => '#B45309',     // Amber - Muted text
        'border' => '#FDE68A',         // Light yellow - Borders
        'background' => '#FFFBEB',
        'card_bg' => '#FFFFFF',
    ],
    'rose' => [
        'name' => 'Rose',
        'primary' => '#EC4899',
        'secondary' => '#F472B6',
        'accent' => '#F9A8D4',
        'success' => '#10B981',
        'warning' => '#F59E0B',
        'danger' => '#EF4444',
        'info' => '#3B82F6',
        'sidebar_bg' => '#831843',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#831843',   // Dark rose - Main text
        'text_secondary' => '#BE185D', // Medium rose - Secondary text
        'text_muted' => '#DB2777',     // Rose - Muted text
        'border' => '#FBCFE8',         // Light rose - Borders
        'background' => '#FFF1F2',
        'card_bg' => '#FFFFFF',
    ],
    'teal' => [
        'name' => 'Teal',
        'primary' => '#14B8A6',
        'secondary' => '#2DD4BF',
        'accent' => '#5EEAD4',
        'success' => '#10B981',
        'warning' => '#F59E0B',
        'danger' => '#EF4444',
        'info' => '#06B6D4',
        'sidebar_bg' => '#134E4A',
        'sidebar_text' => '#FFFFFF',
        'text_primary' => '#134E4A',   // Dark teal - Main text
        'text_secondary' => '#0F766E', // Teal - Secondary text
        'text_muted' => '#0D9488',     // Bright teal - Muted text
        'border' => '#CCFBF1',         // Light teal - Borders
        'background' => '#F0FDFA',
        'card_bg' => '#FFFFFF',
    ],
];
